# Copyright (c) 2020, the THeBE contributors, as
# shown by the AUTHORS file. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

language: cpp

sudo: required
 
matrix:
  include:
    # mac (x86 build)
    - os: osx
      osx_image: xcode10.1
      #addons:
      #   brew:
      #      packages:
      env: 
        - BUILD_TARGET=mac 
    # linux (x64 build)
    - os: linux
      #addons:
        #apt:
          #sources:
            #- george-edison55-precise-backports
         #packages:
           #- cmake
           #- cmake-data
      env: 
        - BUILD_TARGET=linux 


install:
  # Enable execution of the scripts
  - chmod +x tools/travis-scripts/before-install.sh 
  - chmod +x tools/travis-scripts/run-script.sh
  
  # Run install-environment script
  - tools/travis-scripts/before-install.sh

script:
  # Run test script
  - tools/travis-scripts/run-script.sh

cache:
  directories: 
     - opencv-3.1.0
before_cache: 

